"""
dashboard.js and the CSS that styles it ship by DIFFERENT routes.

`static/dashboard.js` is copied straight to the dashboard dir by deploy.sh.
The stylesheet that sizes its elements is generated by build-dashboard.py into
index.html, which only changes when that builder runs. Deploying one without
rebuilding the other is a normal thing to do, and on 2026-08-16 it shipped an
alert pill the size of a dinner plate on every homepage row: the inline SVG
carried a viewBox and a class, the class had no rule on the stale page, and an
SVG with no intrinsic size falls back to 300x150.

So: anything dashboard.js injects that would be unusable at its default size
must carry its own size attributes, and the CSS is the enhancement rather than
the thing holding the page together.

Run from repo root with:
    python3 -m unittest discover tests/
"""
import re
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRAPERS = REPO_ROOT / "tools" / "scrapers"
DASHBOARD_JS = SCRAPERS / "static" / "dashboard.js"
BUILD_DASHBOARD = SCRAPERS / "build-dashboard.py"


def _svg_tags(js: str) -> list:
    """Opening <svg> tags, with JS string concatenation flattened first.

    The tags are built across several quoted fragments joined by `+`, so a
    naive scan of the raw file finds half a tag and draws the wrong conclusion.
    """
    flat = re.sub(r"'\s*\+\s*\n?\s*'", "", js)
    return re.findall(r"<svg\b[^>]*?>", flat)


class InlineSvgSizingTests(unittest.TestCase):
    JS = DASHBOARD_JS.read_text()

    def test_every_inline_svg_carries_its_own_width_and_height(self):
        """Without these, a stale stylesheet renders the icon at 300x150.

        Matched with a leading word boundary on purpose: `stroke-width="1.8"`
        contains the substring `width="`, and an earlier version of this test
        passed on exactly that while the real attribute was missing.
        """
        svgs = _svg_tags(self.JS)
        self.assertTrue(svgs, "no inline SVG found; update this test if that changed")
        for tag in svgs:
            with self.subTest(tag=tag[:70]):
                self.assertRegex(tag, r'(?<![-\w])width="\d')
                self.assertRegex(tag, r'(?<![-\w])height="\d')

    def test_the_icons_are_still_styled_when_the_css_does_load(self):
        """The attributes are the floor, not the design: the CSS sizes in em so
        the glyph tracks the pill's own text."""
        self.assertIn("watch-icon", self.JS)
        css = BUILD_DASHBOARD.read_text()
        self.assertRegex(css, r"\.watch-icon\s*\{[^}]*width:\s*1em")

    def test_classes_dashboard_js_injects_have_rules_in_the_builder(self):
        """A class injected by the JS with no rule anywhere is either dead or a
        latent version-skew bug like the one above."""
        css = BUILD_DASHBOARD.read_text()
        for cls in ("watch-icon", "watch-wrap", "notify-link", "watch-form",
                    "watch-email", "watch-go", "watch-msg", "price-poa"):
            with self.subTest(cls=cls):
                self.assertIn(f".{cls}", css)


if __name__ == "__main__":
    unittest.main()
