#!/usr/bin/env python3
"""
Send a "here's your manage-alerts link" email to a known subscriber.

Triggered by /api/request-manage-link when a subscriber asks for their
preferences URL via the public /manage page.

Usage:
    python3 send_manage_link_email.py EMAIL TOKEN
    python3 send_manage_link_email.py --dry-run EMAIL TOKEN

The token is generated by the caller (subscribe_server.py) and is just
the HMAC-SHA256 of the lowercase email, truncated to 32 chars — i.e. the
same token used by every other preferences/unsubscribe link.
"""

import json
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

SECRETS_DIR = Path("/opt/dale/secrets")
RESEND_ENV = SECRETS_DIR / "resend.env"

FROM_EMAIL = "alerts@mail.treestock.com.au"
FROM_NAME = "treestock.com.au"
SITE_URL = "https://treestock.com.au"


def get_resend_api_key() -> str:
    with open(RESEND_ENV) as f:
        for line in f:
            line = line.strip()
            if line.startswith("RESEND_API_KEY="):
                return line.split("=", 1)[1].strip()
    raise ValueError("RESEND_API_KEY not found in resend.env")


def build_html(email: str, manage_url: str, unsubscribe_url: str) -> str:
    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:560px;margin:0 auto;padding:24px 16px;color:#374151">
  <h2 style="color:#065f46;margin:0 0 12px">Manage your treestock alerts</h2>
  <p style="margin:0 0 16px;font-size:0.95rem;line-height:1.5">
    Someone (hopefully you) asked for the link to manage email alerts for <strong>{email}</strong>.
    Click the button below to change which categories you receive, switch to a weekly digest,
    or stop alerts entirely.
  </p>
  <p style="margin:24px 0;text-align:center">
    <a href="{manage_url}" style="display:inline-block;background:#065f46;color:white;text-decoration:none;padding:10px 24px;border-radius:8px;font-weight:600;font-size:0.95rem">
      Manage my alerts
    </a>
  </p>
  <p style="margin:0 0 8px;font-size:0.85rem;color:#6b7280">
    If you didn't request this, ignore the email — the link only works for {email} and nothing changes until you act on it.
  </p>
  <hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb">
  <p style="font-size:0.75rem;color:#9ca3af;text-align:center;margin:0">
    <a href="{SITE_URL}" style="color:#6b7280">treestock.com.au</a>
    &middot; <a href="{unsubscribe_url}" style="color:#6b7280">Unsubscribe</a>
  </p>
</body></html>"""


def send(email: str, token: str, dry_run: bool = False) -> bool:
    encoded = urllib.parse.quote(email)
    manage_url = f"{SITE_URL}/api/preferences?email={encoded}&token={token}"
    unsubscribe_url = f"{SITE_URL}/unsubscribe?email={encoded}&token={token}"
    subject = "Your treestock.com.au manage-alerts link"
    html = build_html(email, manage_url, unsubscribe_url)

    if dry_run:
        print(f"[DRY RUN] Would send manage-link email to {email}")
        print(f"  Subject: {subject}")
        print(f"  Manage URL: {manage_url}")
        return True

    api_key = get_resend_api_key()
    payload = {
        "from": f"{FROM_NAME} <{FROM_EMAIL}>",
        "to": [email],
        "subject": subject,
        "html": html,
    }
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        "https://api.resend.com/emails",
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read().decode())
            print(f"Manage-link email sent to {email}: {result.get('id', 'ok')}")
            return True
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else str(e)
        print(f"Failed to send manage-link email to {email}: HTTP {e.code} — {body}", file=sys.stderr)
        return False
    except Exception as e:
        print(f"Failed to send manage-link email to {email}: {e}", file=sys.stderr)
        return False


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) < 2:
        print("Usage: send_manage_link_email.py [--dry-run] EMAIL TOKEN")
        sys.exit(1)
    email = args[0].strip().lower()
    token = args[1].strip()
    ok = send(email, token, dry_run=dry_run)
    sys.exit(0 if ok else 1)
